In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Customer%20Purchase.csv')

In [3]:
df

    Customer ID  Age  Gender Education   Review Purchased
0          1021   30  Female    School  Average        No
1          1022   68  Female        UG     Poor        No
2          1023   70  Female        PG     Good        No
3          1024   72  Female        PG     Good        No
4          1025   16  Female        UG  Average        No
5          1026   31  Female    School  Average       Yes
6          1027   18    Male    School     Good        No
7          1028   60  Female    School     Poor       Yes
8          1029   65  Female        UG  Average        No
9          1030   74    Male        UG     Good       Yes
10         1031   98  Female        UG     Good       Yes
11         1032   74    Male        UG     Good       Yes
12         1033   51    Male    School     Poor        No
13         1034   57  Female    School  Average        No
14         1035   15    Male        PG     Poor       Yes
15         1036   75    Male        UG     Poor        No
16         1037   59    Male        UG     Poor       Yes
17         1038   22  Female        UG     Poor       Yes
18         1039   19    Male    School     Good        No
19         1040   97    Male        PG     Poor       Yes
20         1041   57  Female    School  Average       Yes
21         1042   32    Male        PG  Average        No
22         1043   18  Female        PG     Poor       Yes
23         1044   96  Female    School     Good        No
24         1045   16  Female        PG  Average       Yes
25         1046   57  Female    School     Good        No
26         1047   53  Female        PG     Poor        No
27         1048   69  Female        PG     Poor        No
28         1049   48    Male    School     Poor        No
29         1050   83  Female        UG  Average       Yes
30         1051   73    Male        UG  Average        No
31         1052   22  Female    School     Poor       Yes
32         1053   92    Male        UG  Average       Yes
33         1054   89  Female        PG     Good       Yes
34         1055   86    Male    School  Average        No
35         1056   74    Male    School     Poor       Yes
36         1057   34  Female        UG     Good       Yes
37         1058   94    Male        PG  Average       Yes
38         1059   45  Female    School     Good        No
39         1060   76    Male        PG     Poor        No
40         1061   39    Male    School     Good        No
41         1062   23    Male        PG     Good       Yes
42         1063   30  Female        PG     Good       Yes
43         1064   27    Male        PG     Poor        No
44         1065   77  Female        UG  Average        No
45         1066   61    Male        PG     Poor       Yes
46         1067   64  Female        PG     Poor        No
47         1068   38  Female        PG     Good       Yes
48         1069   39  Female        UG     Good       Yes
49         1070   25  Female        UG     Good        No

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer ID  50 non-null     int64
 1   Age          50 non-null     int64
 2   Gender       50 non-null     object
 3   Education    50 non-null     object
 4   Review       50 non-null     object
 5   Purchased    50 non-null     object
dtypes: int64(2), object(4)
memory usage: 2.5+ KB

In [6]:
df.describe()

       Customer ID        Age
count     50.00000  50.000000
mean    1045.50000  54.160000
std       14.57738  25.658161
min     1021.00000  15.000000
25%     1033.25000  30.250000
50%     1045.50000  57.000000
75%     1057.75000  74.000000
max     1070.00000  98.000000

In [7]:
df.head()

   Customer ID  Age  Gender Education   Review Purchased
0         1021   30  Female    School  Average        No
1         1022   68  Female        UG     Poor        No
2         1023   70  Female        PG     Good        No
3         1024   72  Female        PG     Good        No
4         1025   16  Female        UG  Average        No

In [8]:
df.isnull().sum()

Customer ID    0
Age            0
Gender         0
Education      0
Review         0
Purchased      0
dtype: int64

In [11]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Education', 'Review', 'Purchased'], dtype='object')

In [12]:
y = df['Purchased']

In [13]:
X = df.drop(['Customer ID','Purchased'],axis = 1)

In [15]:
df.head()

   Customer ID  Age  Gender Education   Review Purchased
0         1021   30  Female    School  Average        No
1         1022   68  Female        UG     Poor        No
2         1023   70  Female        PG     Good        No
3         1024   72  Female        PG     Good        No
4         1025   16  Female        UG  Average        No

In [16]:
# encoding categorical variable
X.replace({'Review':{'Poor':0,'Average':1,'Good':2}},inplace=True)
X.replace({'Gender':{'Male':0,'Female':1}},inplace = True)
X.replace({'Education':{'School':0,'UG':1,'PG':2}},inplace=True)

In [17]:
X.head()

   Age  Gender  Education  Review
0   30       1          0       1
1   68       1          1       0
2   70       1          2       2
3   72       1          2       2
4   16       1          1       1

In [74]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.7,random_state=2529)

In [75]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((35, 4), (15, 4), (35,), (15,))

In [76]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

In [77]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [78]:
y_pred = model.predict(X_test)

In [79]:
y_pred

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No'], dtype=object)

In [80]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [81]:
confusion_matrix(y_test,y_pred,)

array([[7, 0],
       [4, 4]])

In [82]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

          No       0.64      1.00      0.78         7
         Yes       1.00      0.50      0.67         8

    accuracy                           0.73        15
   macro avg       0.82      0.75      0.72        15
weighted avg       0.83      0.73      0.72        15

In [83]:
accuracy_score(y_test,y_pred)

0.7333333333333333